import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Blog | Contact",
    description: "Generated by This is business",
};

function Contact() {
  return (
    <div>
      Hello this is contact page
    </div>
  )
}

export default Contact
