import Image from "next/image";
import Head from 'next/head';
import type { Metadata } from "next";
import HomePage from "@/app/components/ui/home"

export const metadata: Metadata = {
  title: "Blog | Home",
  description: "Generated by This is business",
};

export default function Home() {
  return (
    <main className="">
      <HomePage/>
    </main>
  );
}